[workspace]
members = ["crates/rypsok-core", "crates/rypsok"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
repository = "https://github.com/nabbisen/rypsok"
authors = ["nabbisen"]

[workspace.dependencies]
rypsok-core = { path = "crates/rypsok-core", version = "0.1.0" }
clap = { version = "4.5", features = ["derive"] }
rmcp = { version = "=3.5.0", default-features = false, features = ["server", "transport-io"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
dbg_macro = "deny"
