[book]
title = "rypsok"
description = "Headless meta-search service for AI agents"
authors = ["nabbisen"]
language = "en"
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "light"
